import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import {UserProvider} from "@/context/user";
import {CartProvider} from "@/context/cart";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "PI Frontend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UserProvider>
      <CartProvider>
        <html lang="en">
          <body className={inter.className}>
            <div className="min-h-screen flex flex-col">
              <Navbar />
              <main className="flex flex-grow justify-center ">{children}</main>
              <Footer />
            </div>
          </body>
        </html>
      </CartProvider>
    </UserProvider>
  );
}
