import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import {ProductsProvider} from "@/context/products";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "PI Frontend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ProductsProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          <main className="flex flex-col items-center justify-center h-screen">
            {children}
          </main>
          <Footer />
        </body>
      </html>
    </ProductsProvider>
  );
}
